use super::Result;
use base64::{Engine, engine::general_purpose::STANDARD};
use serde_json::{Value, json};
use std::{
    collections::BTreeMap,
    fs,
    io::{self, Read, Write},
    os::unix::fs::{OpenOptionsExt, PermissionsExt},
    path::Path,
    sync::atomic::{AtomicU64, Ordering},
};
static NONCE: AtomicU64 = AtomicU64::new(0);

fn valid_key(key: &str) -> bool {
    let Some(suffix) = key.strip_prefix("JELLY_") else {
        return false;
    };
    !suffix.is_empty()
        && suffix
            .bytes()
            .all(|b| b.is_ascii_uppercase() || b.is_ascii_digit() || b == b'_')
}
fn safe_value(value: &str) -> bool {
    !value.contains(['\n', '\r', '\0'])
}
fn parse(input: &str) -> Result<BTreeMap<String, String>> {
    let mut values = BTreeMap::new();
    for (number, line) in input.lines().enumerate() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let (key, raw) = line
            .split_once('=')
            .ok_or_else(|| format!("line {}: unsupported environment assignment", number + 1))?;
        let key = key.trim();
        if !valid_key(key) {
            return Err(format!("line {}: invalid JELLY_ key", number + 1).into());
        }
        let raw = raw.trim();
        let value = if raw.starts_with('"') {
            serde_json::from_str::<String>(raw)?
        } else if raw.starts_with('\'') && raw.ends_with('\'') && raw.len() >= 2 {
            raw[1..raw.len() - 1].to_owned()
        } else {
            raw.to_owned()
        };
        if !safe_value(&value) {
            return Err(format!("line {}: multiline/NUL value", number + 1).into());
        }
        values.insert(key.to_owned(), value);
    }
    Ok(values)
}
pub fn read_command(path: &Path) -> Result<()> {
    let text = match fs::read_to_string(path) {
        Ok(s) => s,
        Err(e) if e.kind() == io::ErrorKind::NotFound => String::new(),
        Err(e) => return Err(e.into()),
    };
    for (key, value) in parse(&text)? {
        println!("{key}\t{}", STANDARD.encode(value));
    }
    Ok(())
}
fn atomic_write(path: &Path, content: &str) -> Result<()> {
    let parent = path
        .parent()
        .filter(|p| !p.as_os_str().is_empty())
        .unwrap_or(Path::new("."));
    fs::create_dir_all(parent)?;
    let mut tempfile = None;
    for _ in 0..30 {
        let candidate = parent.join(format!(
            ".jelly-maint-{}-{}",
            std::process::id(),
            NONCE.fetch_add(1, Ordering::Relaxed)
        ));
        match fs::OpenOptions::new()
            .write(true)
            .create_new(true)
            .mode(0o600)
            .open(&candidate)
        {
            Ok(mut f) => {
                tempfile = Some(candidate.clone());
                let outcome = (|| -> Result<()> {
                    f.write_all(content.as_bytes())?;
                    f.flush()?;
                    f.sync_all()?;
                    fs::rename(&candidate, path)?;
                    Ok(())
                })();
                if outcome.is_err() {
                    let _ = fs::remove_file(&candidate);
                }
                outcome?;
                fs::set_permissions(path, fs::Permissions::from_mode(0o600))?;
                if let Ok(dir) = fs::File::open(parent) {
                    let _ = dir.sync_all();
                }
                break;
            }
            Err(e) if e.kind() == io::ErrorKind::AlreadyExists => continue,
            Err(e) => return Err(e.into()),
        }
    }
    if tempfile.is_none() {
        return Err("could not allocate temporary file".into());
    }
    Ok(())
}
fn write_values(path: &Path, values: &Value) -> Result<()> {
    let object = values.as_object().ok_or("expected a JSON object")?;
    let mut body = String::from("# Generated by ./scripts/dev.sh setup\n");
    for (key, value) in object {
        if !valid_key(key) {
            return Err(format!("invalid environment key {key}").into());
        }
        let v = value.as_str().ok_or("expected string value")?;
        if !safe_value(v) {
            return Err("multiline/NUL value".into());
        }
        body.push_str(key);
        body.push('=');
        body.push_str(&serde_json::to_string(v)?);
        body.push('\n');
    }
    atomic_write(path, &body)
}
pub fn write_rows_command(path: &Path) -> Result<()> {
    let mut text = String::new();
    io::stdin().read_to_string(&mut text)?;
    let mut values = serde_json::Map::new();
    for (i, line) in text.lines().enumerate() {
        let (key, encoded) = line
            .split_once('\t')
            .ok_or_else(|| format!("row {}: missing tab", i + 1))?;
        if !valid_key(key) {
            return Err(format!("row {}: invalid key", i + 1).into());
        }
        if values.contains_key(key) {
            return Err(format!("row {}: duplicate key", i + 1).into());
        }
        let value = String::from_utf8(STANDARD.decode(encoded)?)?;
        if !safe_value(&value) {
            return Err(format!("row {}: multiline/NUL", i + 1).into());
        }
        values.insert(key.to_owned(), Value::String(value));
    }
    write_values(path, &Value::Object(values))
}
pub fn write_command(path: &Path) -> Result<()> {
    let mut input = String::new();
    io::stdin().read_to_string(&mut input)?;
    let data: Value = serde_json::from_str(&input)?;
    write_values(path, &data)
}
pub fn config_set(path: &Path, section: &str, key: &str, value: &str) -> Result<()> {
    if section.is_empty()
        || key.is_empty()
        || !section
            .bytes()
            .all(|b| b.is_ascii_alphanumeric() || b == b'_')
        || !key.bytes().all(|b| b.is_ascii_alphanumeric() || b == b'_')
    {
        return Err("invalid section or key".into());
    }
    let original = fs::read_to_string(path)?;
    let mut lines: Vec<String> = original.lines().map(str::to_owned).collect();
    let header = format!("[{section}]");
    let mut inside = false;
    let mut found_section = false;
    let mut found_key = false;
    let rendered = if matches!(value, "true" | "false") || value.parse::<i64>().is_ok() {
        value.to_owned()
    } else {
        serde_json::to_string(value)?
    };
    for line in &mut lines {
        let trimmed = line.trim();
        if trimmed.starts_with('[') && trimmed.ends_with(']') {
            inside = trimmed == header;
            found_section |= inside;
            continue;
        }
        if inside
            && trimmed
                .split_once('=')
                .is_some_and(|(candidate, _)| candidate.trim() == key)
        {
            *line = format!("{key} = {rendered}");
            found_key = true;
            break;
        }
    }
    if !found_section {
        return Err(format!("missing [{section}] in {}", path.display()).into());
    }
    if !found_key {
        return Err(format!("missing {section}.{key} in {}", path.display()).into());
    }
    let content = lines.join("\n") + "\n";
    // Config is not a secret; retain existing mode, write atomically.
    let mode = fs::metadata(path)?.permissions().mode() & 0o777;
    atomic_write(path, &content)?;
    fs::set_permissions(path, fs::Permissions::from_mode(mode))?;
    Ok(())
}
pub fn test_security() -> Result<()> {
    let root = std::env::temp_dir().join(format!("jelly-maint-security-{}", std::process::id()));
    fs::create_dir(&root)?;
    let outcome = (|| -> Result<()> {
        let file = root.join(".env");
        let marker = root.join("unexpected-execution");
        let injection = format!("$(touch {}) spaces # $HOME", marker.display());
        let inputs = json!({"JELLY_MCP_TOKEN":injection,"JELLY_PUBLIC_URL":"https://example.com/?a=1&b=2","JELLY_TELEGRAM_CHAT_ID":"é-special"});
        write_values(&file, &inputs)?;
        assert_eq!(fs::metadata(&file)?.permissions().mode() & 0o777, 0o600);
        let values = parse(&fs::read_to_string(&file)?)?;
        assert_eq!(values["JELLY_MCP_TOKEN"], injection);
        assert!(!marker.exists());
        assert!(parse("JELLY_MCP_TOKEN=\"unterminated\n").is_err());
        assert!(parse("PATH=/tmp/unsafe\n").is_err());
        assert_eq!(
            parse("JELLY_MCP_TOKEN=$(touch /tmp/NEVER)\n")?["JELLY_MCP_TOKEN"],
            "$(touch /tmp/NEVER)"
        );
        let config = root.join("config.toml");
        fs::write(
            &config,
            "[page]\nruntime = true\n[diagnostics]\nperf_log = false\n",
        )?;
        config_set(&config, "page", "runtime", "false")?;
        assert_eq!(
            toml::from_str::<toml::Value>(&fs::read_to_string(&config)?)?["page"]["runtime"]
                .as_bool(),
            Some(false)
        );
        let before = fs::read(&config)?;
        assert!(config_set(&config, "missing", "runtime", "false").is_err());
        assert_eq!(before, fs::read(&config)?);
        // Execute only the validator function from the checked-in cleanup
        // script; never run its service-stop/removal commands.
        let cleanup_script = fs::read_to_string(super::root().join("scripts/clean-runtime.sh"))?;
        let function = cleanup_script
            .split_once("validate_cleanup_target() {")
            .ok_or("missing cleanup guard")?
            .1
            .split_once("\n}\n")
            .ok_or("unterminated cleanup guard")?
            .0;
        let test = format!(
            r#"
set -euo pipefail
ROOT=/data/github/jelly
HOME=/home/test
validate_cleanup_target() {{{function}
}}
for path in / /data /etc /tmp /home /data/github/jelly /data/other-project /data/../data; do
    if validate_cleanup_target "$path" >/dev/null 2>&1; then
        echo "unsafe cleanup target accepted: $path" >&2
        exit 1
    fi
done
validate_cleanup_target /data/jelly-runtime
validate_cleanup_target /data/.jelly-build
"#
        );
        if !std::process::Command::new("bash")
            .args(["-c", &test])
            .status()?
            .success()
        {
            return Err("cleanup script guards rejected test cases".into());
        }
        Ok(())
    })();
    let _ = fs::remove_dir_all(&root);
    outcome?;
    println!(
        "PASS: Rust environment parsing/serialization, atomic permissions, non-execution and TOML edit guards"
    );
    Ok(())
}
#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn reject_bad_env() {
        assert!(parse("PATH=x").is_err());
        assert!(parse("JELLY_X=\"unterminated").is_err());
    }
    #[test]
    fn safely_keep_literal_shell() {
        assert_eq!(parse("JELLY_X=$(id)\n").unwrap()["JELLY_X"], "$(id)");
    }
}
