use jelly::{ArgSpec, category_specs, primitive_specs, tool_category_specs, tool_specs};
use std::{env, fs, path::PathBuf};

fn md(s: &str) -> String {
    s.replace('|', "\\|").replace('\n', " ")
}

fn args(specs: &[ArgSpec]) -> String {
    if specs.is_empty() {
        return "—".into();
    }
    specs
        .iter()
        .map(|a| {
            let inner = format!("{}:{}", a.name, a.type_name());
            if a.required {
                format!("`{inner}`")
            } else {
                format!("`[{inner}]`")
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}

fn render() -> String {
    let mut out = String::new();
    out.push_str("<!-- GENERATED by scripts/build-tool-index.sh. DO NOT EDIT. -->\n\n");
    out.push_str("# jelly tool index\n\n");
    out.push_str("This file is generated from the Rust browser-primitive and system-tool registries. Those registries are the source of truth.\n\n");

    out.push_str("## Browser capability groups\n\n");
    out.push_str("| Category | Description |\n| --- | --- |\n");
    for category in category_specs {
        out.push_str(&format!(
            "| `{}` | {} |\n",
            md(category.name),
            md(category.description)
        ));
    }

    out.push_str("\n## System capability groups\n\n");
    out.push_str("| Category | Description |\n| --- | --- |\n");
    for category in tool_category_specs {
        out.push_str(&format!(
            "| `{}` | {} |\n",
            md(category.name),
            md(category.description)
        ));
    }

    out.push_str("\n## Browser primitives\n\n");
    out.push_str(
        "| Tool | Category | Usage | Arguments | Description |\n| --- | --- | --- | --- | --- |\n",
    );
    for spec in primitive_specs {
        out.push_str(&format!(
            "| `{}` | `{}` | `{}` | {} | {} |\n",
            md(spec.name),
            md(spec.category),
            md(spec.usage),
            args(spec.args),
            md(spec.description),
        ));
    }
    out.push_str("\nArgument types: `target` accepts stable `@eN` refs, `css:<selector>`, `text:<exact text>`, or plain exact text. Optional arguments are shown in brackets.\n\n");

    out.push_str("## System and integration tools\n\n");
    out.push_str("These tools are executable capabilities that intentionally do not require a shared `BrowserSession` primitive handler.\n\n");
    out.push_str("| Tool | Category | Usage | Description |\n| --- | --- | --- | --- |\n");
    for spec in tool_specs {
        out.push_str(&format!(
            "| `{}` | `{}` | `{}` | {} |\n",
            md(spec.name),
            md(spec.category),
            md(spec.usage),
            md(spec.description),
        ));
    }

    out.push_str("\n## Discovery CLI\n\n");
    out.push_str("Discovery searches both registries while preserving the browser/system distinction. Full metadata is loaded only when needed.\n\n");
    out.push_str("```text\n");
    out.push_str("agent-discover capabilities\n");
    out.push_str("agent-discover list [category]\n");
    out.push_str("agent-discover category <name>\n");
    out.push_str("agent-discover search <query> [--limit N]\n");
    out.push_str("agent-discover schema <tool>\n");
    out.push_str("```\n");
    out
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let check = env::args().skip(1).any(|arg| arg == "--check");
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(".agent/tools/index.md");
    let generated = render();
    if check {
        let current = fs::read_to_string(&path).unwrap_or_default();
        if current != generated {
            return Err(format!(
                "{} is stale; run scripts/build-tool-index.sh",
                path.display()
            )
            .into());
        }
        println!("Tool index is current: {}", path.display());
    } else {
        fs::write(&path, generated)?;
        println!("Generated {}", path.display());
    }
    Ok(())
}
