#!/usr/bin/env python3
"""Parse Jelly's data-only .env values without executing shell expressions.

Read values with `read PATH` (tab-separated name and Base64 value); write with
`write PATH`, reading JSON key/value pairs from stdin. Deliberately accepts
plain values or JSON-quoted strings and never expands variables or commands.
"""
import base64
import json
import os
from pathlib import Path
import re
import sys
import tempfile

KEY = re.compile(r"JELLY_[A-Z0-9_]+\Z")


def read_values(path: Path) -> dict[str, str]:
    values = {}
    if not path.exists():
        return values
    for number, line in enumerate(path.read_text().splitlines(), 1):
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        key, sep, raw = line.partition('=')
        if not sep or not KEY.fullmatch(key.strip()):
            raise ValueError(f'{path}:{number}: unsupported environment assignment')
        raw = raw.strip()
        if raw.startswith('"'):
            value = json.loads(raw)
            if not isinstance(value, str):
                raise ValueError(f'{path}:{number}: expected a string')
        elif raw.startswith("'") and raw.endswith("'"):
            value = raw[1:-1]
        else:
            value = raw
        if '\x00' in value or '\n' in value or '\r' in value:
            raise ValueError(f'{path}:{number}: multiline/NUL values are not supported')
        values[key.strip()] = value
    return values


def main() -> None:
    mode, filename = sys.argv[1:]
    path = Path(filename)
    if mode == 'read':
        for key, value in read_values(path).items():
            print(key + '\t' + base64.b64encode(value.encode()).decode())
    elif mode == 'write':
        values = json.load(sys.stdin)
        if not isinstance(values, dict) or not all(KEY.fullmatch(k) and isinstance(v, str) for k, v in values.items()):
            raise ValueError('expected an object of JELLY_ string values')
        if any(any(c in v for c in '\x00\r\n') for v in values.values()):
            raise ValueError('multiline/NUL values are not supported')
        path.parent.mkdir(parents=True, exist_ok=True)
        fd, temporary = tempfile.mkstemp(prefix=path.name + '.', dir=path.parent)
        try:
            with os.fdopen(fd, 'w') as out:
                os.fchmod(out.fileno(), 0o600)
                out.write('# Generated by ./quickstart.sh\n')
                for k, v in values.items():
                    out.write(k + '=' + json.dumps(v, ensure_ascii=False) + '\n')
                out.flush()
                os.fsync(out.fileno())
            os.replace(temporary, path)
        finally:
            if os.path.exists(temporary):
                os.unlink(temporary)
    else:
        raise ValueError('expected read or write')


if __name__ == '__main__':
    try:
        main()
    except (ValueError, json.JSONDecodeError, OSError) as exc:
        print(f'Jelly environment data: {exc}', file=sys.stderr)
        sys.exit(2)
